### ISSUE TITLE
Action has no kind set

### ISSUE THREAD

**Issue by chimon2000** [apache/incubator-openwhisk-wskdeploy#1005]
When attempting to execute `wskdeploy -m manifest.yml`, I get an error: "Action [action_name] has no kind set.

![image](https://user-images.githubusercontent.com/6907797/47958119-2ba5a100-df9b-11e8-9bb7-ca68f4824c14.png)

See manifest.yaml below

```yaml
packages:
    helloworld:
        actions:
            helloJS:
                function: src/hello.js
                runtime: nodejs:8
            hello-world-nodejs-delay:
                function: src/hello-delay.js
                runtime: nodejs:8

```

I have tried every version of **wskdeploy** back to v09.7
