### ISSUE TITLE
Can't specify limits on Sequences

### ISSUE THREAD

**Issue by TPei** [apache/incubator-openwhisk-wskdeploy#1042]
When settings limits on a sequence, such as
```yaml
packages:
  sequence_demo:
    actions:
      my_action:
        function: main.js
        limits:
          memorySize: 1024
    sequences:
      my_sequence:
        actions: >
          my_action,
          my_action
        limits:
          memorySize: 1024
```
it causes an error:
```
Error: manifest_parser.go [115]: [ERROR_YAML_PARSER_ERROR]: File: [manifest.yml]: 
==> yaml: unmarshal errors:
==> line 37: field limits not found in struct parsers.Sequence
```

However, Sequence memory limits can be set via the regular cli:
`wsk action update my_sequence --memory 1024`
