### ISSUE TITLE
Change the spec to add the description of  `sequences` for sequences

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-wskdeploy#108]
The current implementation is using a separate entity for sequences, other than `composition entity`. 
Refer to [manifest.yaml](https://github.com/openwhisk/openwhisk-wskdeploy/blob/master/tests/testcases/whiskbot/manifest.yaml) in test case `wskbot` and [manifest.yaml](https://github.com/openwhisk/openwhisk-wskdeploy/blob/master/tests/testcases/openstack/manifest.yaml) in test case `openstack`.
```
    seqeunces:
      newbot: 
        actions: oauth/login, decrypt, newbot-setup
        annotations:
          web-export:
            type: string
      getSetup:
        actions: getWhiskAuthAndNamespace, encrypt, getSetupURL
      setup-backend:
        actions: provision-backend, configure-backend
```

@mrutkows If you aren't against, will you change the specification?
