### ISSUE TITLE
specification and specification are not consistent for parameter using single line syntax

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-wskdeploy#216]
According to spec 0.8.3 https://github.com/openwhisk/openwhisk-wskdeploy/blob/master/specification/openwhisk_v0.8.3.pdf

inputs is defined as list of properties
each property can be expressed only as single line or complex object

options 1 (single line)
```
<parameterName>: <any>
```
```
inputs:
  prop1: string
  prop2: boolean
  prop3: number
```

option 2 (object)
```
<parameterName>:
  type: <any>
  description: <string>
  required: <boolean>
  default: <any>
  status: <string>
  schema: <OpenAPI Schema Object>
```
```
inputs
  prop1:
    type: string
    default: Paul
  prop2:
     type: boolean
      default: false
   prop3:
      type: number
      default: 42
```

The following usecases have a wrong yaml
https://github.com/openwhisk/openwhisk-wskdeploy/blob/master/tests/usecases/opentest/manifest.yaml
```
      inputs:
        cron: 0/30 * * * * *
        trigger_payload: '{"message":"Hello Friend"}'
```
https://github.com/openwhisk/openwhisk-wskdeploy/blob/master/tests/usecases/helloworld/manifest.yaml
```
  actions:
    hello:
      version: 2.0
      location: actions/greeting.js
      runtime: nodejs:6
      inputs:
        name: Paul
        place: Boston
    helloworld:
      version: 1.0
      location: actions/greeting2.js
      runtime: nodejs:6
      inputs:
        name: Bernie
        place: Vermont
```

**Comment by csantanapr** [comment]
According to @paulcastro Specification document 0.8.3 is wrong and needs to be updated, to specify that using a single-line with a type or value is allowed.

![image](https://cloud.githubusercontent.com/assets/1094878/24424529/e87313ca-13ce-11e7-92e9-65c1bd76b10e.png)

The only cautious thing to watch out, is if the user really wants a value of literal "string" it would need to use the multi-line format
```
inputs:
   name:
     type: string
      default: string
       description: Yes my name is string !
```

**Comment by paulcastro** [comment]
Per discussion with @lionelvillard it makes sense to support the following use cases:

inline:
```
inputs:
    myParameter: Hello
```

complex object:
```
inputs
    myParameter:
         type: string
         default: Hello
```

It may make sense to say "value" instead of default:
```
inputs
    myParameter:
         type: string
         value: Hello
```

This would work to be explicit about handling JSON objects if we allow a JSON type

```
inputs
    myParameter:
         type: json
         default: '{"msg":"Hello"}'
```

**Comment by lionelvillard** [comment]
I would like to propose something slightly different. The common case is passing JSON as input value so the inline value should be parsed as JSON.

inline

```
inputs:
    myParameter: <JSON Value>
```

which is equivalent to

```
inputs:
    myParameter: 
       type: <JSON Type>    # One of the JSON Schema types or an array.
       value: <JSON Value>
```

The uncommon case to pass a JSON as a string value is still supported:

```
inputs:
    myParameter: 
       type: string
       value: '{"msg":"Hello"}'
```
