### ISSUE TITLE
Support concept of modular projects in deployment.yaml

### ISSUE THREAD

**Issue by paulcastro** [apache/incubator-openwhisk-wskdeploy#234]
Referencing Issue #173, there is a use case where a single project can consist of modules, where each module has it's own manifest file.  The project uses a deployment file to select what pieces of each module are needed and wire together the project.
 
We are considering dependencies in Issue #41, however the model in #41 is that dependencies are stand-alone projects that get integrated into a larger solution.  In this issue, a module may not be stand-alone (e.g. not in its own rep) and functions mainly as an organizational construct when developing large, complex projects.

We need to extend a deployment file to handle this case.

**Comment by daisy-ycguo** [comment]
I think we have supported this feature with PR #519.
@mrutkows @pritidesai Hope you can verify it when you have time. Thank you.

**Comment by pritidesai** [comment]
With PR #519, we added support for `packages` such as:

```
packages:
    package-1:
        actions:
            action-1:
            ...
    package-2:
        actions:
            action-2:
            ...
    package-3:
        actions:
            action-3:
            ...
```
