### ISSUE TITLE
Invalid Deployment. yaml for use case "webhook"

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#296]
The deployment YAML contains references to "WskTool" (invalid deleted repo.). It also includes an Daisy's username as default value where we should not be including developer usernames if possible in test files.

```
pplication:
  name: wskdeploy-samples
  namespace: guest

  packages:
    git_webhook:
      credential: 23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP

      feeds:
        webhook:
          #we treat the inputs as parameters besides --feed.
          inputs:
            username: daisy-ycguo 
            repository: https://github.com/openwhisk/wsktool.git
            accessToken:
            events: PUSH
            endpoint: openwhisk.ng.bluemix.net
```

In addition, we should try not to use "guest" namespace (but use '_') default namespace where possible to allow testing/deployment on multiple target providers of openwhisk.
