### ISSUE TITLE
Support of list for openwhisk entities

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-wskdeploy#304]
We currently support multiple entities like triggers, actions and rules, described under one element, but in different sub-elements. For exmaple,
```
triggers:
        # Trigger named “data-inserted-trigger”
        # Creating trigger to fire events when data is inserted into database
        data-inserted-trigger:
            source: openwhisk-cloudant/changes
            inputs:
                dbname: $CLOUDANT_DATABASE
        data-inserted-trigger_1:
            source: openwhisk-cloudant/changes
            inputs:
                dbname: $CLOUDANT_DATABASE
```
We should extend to support entities defined in list, since list is a commonly supported in yaml file, like
```
triggers:
        - name: data-inserted-trigger:
           source: openwhisk-cloudant/changes
           inputs:
                dbname: $CLOUDANT_DATABASE
        - name: data-inserted-trigger1:
           source: openwhisk-cloudant/changes
           inputs:
                dbname: $CLOUDANT_DATABASE
```
