### ISSUE TITLE
Wondering why triggers are updated with overwrite set to false

### ISSUE THREAD

**Issue by zachschultz** [apache/incubator-openwhisk-wskdeploy#305]
I have a wskdeploy manifest yaml file that looks like:

```
package:
  name: messagehub-trigger
  version: 1.0
  license: Apache-2.0
  namespace: _
  dependencies:
    openwhisk-messagehub:
      location: /whisk.system/messaging
      inputs:
        kafka_brokers_sasl: $KAFKA_BROKERS
        user: $MESSAGEHUB_USER
        password: $MESSAGEHUB_PASS
        kafka_admin_url: $KAFKA_ADMIN_URL
  actions:
    process-message:
      location: actions/process-message.js
  triggers:
    message-received-trigger:
      source: openwhisk-messagehub/messageHubFeed
      inputs:
        isJSONData: true
        topic: $KAFKA_TOPIC
  rules:
      log-message-rule:
        trigger: message-received-trigger
        action: messagehub-trigger/process-message
```

When I changed the `source` of the `message-received-trigger` and ran wskdeploy I noticed that OpenWhisk didn't actually change the trigger, and after running with `verbose` I saw that the request was:

```
REQUEST:
[PUT]	https://openwhisk.ng.bluemix.net:443/api/v1/namespaces/_/triggers/message-received-trigger?overwrite=false
```

Why is it that everything else is sent with `overwrite=true` but trigger creations are sent with `overwrite=false`?
