### ISSUE TITLE
Switch to yaml.UnmarshalStrict()

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#309]
[manifest_parser.Unmarshal()](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/parsers/manifest_parser.go#L61) method is using [yaml.Unmarshal()](https://github.com/go-yaml/yaml/blob/v2/yaml.go#L90). Evaluate and change it to call [yaml.UnmarshalStrict()](https://github.com/go-yaml/yaml/blob/v2/yaml.go#L86).

Notice a test case in [manifest_parser_test.go](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/308/files#diff-d2c21d01a5f4cb82e4fa482087e7f6a2R201) (PR # 308):

When a manifest_parser.Unmarshal() is initiated with invalid manifest data (package section is missing):

```
  actions:
    helloNodejs:
      location: actions/hello.js
      runtime: nodejs:6
    helloJava:
      location: actions/hello.java`
```
manifest_parser.Unmarshal() does not report any error even though `Package` section is missing. 

We should report error in case of a required YAML members are not specified in manifest file.
