### ISSUE TITLE
Action limits in Manifest file is ignored

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#312]
We describe in WskDeploy specification that wskdeploy supports map of limit keys and values under `limits` section, e.g.:

```
package:
  name: helloworld
  actions:
    hello:
      location: ../tests/usecases/helloworld/actions/hello.js
      limits:
        timeout: 60
        memorySize: 128
        logSize: 1
        concurrentActivations: 10
        userInvocationRate: 50
        codeSize: 1024
        parameterSize: 128
```

But this `limits` section is ignored by manifest_parser. `Action` is defined without such limits section at [yamlparser.go](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/parsers/yamlparser.go#L51) 

In addition to wskdeploy, [openwhisk client](https://github.com/apache/incubator-openwhisk-client-go/blob/master/whisk/shared.go#L76) only has support for three such limits:

```
type Limits struct {
    Timeout *int `json:"timeout,omitempty"`
    Memory  *int `json:"memory,omitempty"`
    Logsize *int `json:"logs,omitempty"`
}
```
