### ISSUE TITLE
Action deployed with .php extension defaulted to a Node runtime

### ISSUE THREAD

**Issue by zachschultz** [apache/incubator-openwhisk-wskdeploy#317]
My manifest file looks like:

```
# This manifest file reads the following env. variables:
#   KAFKA_BROKERS
#   MESSAGEHUB_USER
#   MESSAGEHUB_PASS
#   KAFKA_TOPIC

package:
  name: messagehub-trigger
  version: 1.0
  license: Apache-2.0
  namespace: _
  dependencies:
    openwhisk-messagehub:
      location: /whisk.system/messaging
      inputs:
        kafka_brokers_sasl: $KAFKA_BROKERS
        user: $MESSAGEHUB_USER
        password: $MESSAGEHUB_PASS
        kafka_admin_url: $KAFKA_ADMIN_URL
  actions:
    process-message:
      location: runtimes/php/actions/process-message.php
  triggers:
    message-received-trigger:
      source: openwhisk-messagehub/messageHubFeed
      inputs:
        isJSONData: true
        topic: $KAFKA_TOPIC
  rules:
      log-message-rule:
        trigger: message-received-trigger
        action: messagehub-trigger/process-message
```

After running `wskdeploy` I noticed that my deployed action happened to be the Node runtime, and naturally didn't run correctly.
