### ISSUE TITLE
Change manifest file to not need specific location of action in rules and sequences

### ISSUE THREAD

**Issue by zachschultz** [apache/incubator-openwhisk-wskdeploy#394]
Right now when we write the location of an action for a rule and sequence in the manifest file it needs to be in the format `PACKAGE_NAME/ACTION_NAME`, i.e.

```
package:
    name: cloudant-trigger
   ...
    actions:
        process-change:
            function: actions/process-change.js
    sequences:
        process-change-cloudant-sequence:
            actions: openwhisk-cloudant/read, cloudant-trigger/process-change
    rules:
        log-change-rule:
            trigger: data-inserted-trigger
            action: cloudant-trigger/process-change-cloudant-sequence
```

It would be nice if we only needed to write `process-change` and `process-change-cloudant-sequence` instead, especially if we want to allow users to change the package name with an environment variable. Replacing just `package.name` is much easier than having to scrape through the entire manifest file to find and replace the instances of the package.name.

**Comment by daisy-ycguo** [comment]
@zachschultz Will you try blow manifest, removing `cloudant-trigger/` from `cloudant-trigger/process-change` and `cloudant-trigger/process-change-cloudant-sequence`? I think it works. Let me know how it works in your test env.

```
package:
    name: cloudant-trigger
   ...
    actions:
        process-change:
            function: actions/process-change.js
    sequences:
        process-change-cloudant-sequence:
            actions: openwhisk-cloudant/read, process-change
    rules:
        log-change-rule:
            trigger: data-inserted-trigger
            action: process-change-cloudant-sequence
```
