### ISSUE TITLE
Concurrent issues when running integration tests accessing the same resources

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-wskdeploy#398]
Integration tests like triggerrule_test and flags_test running together will lead to this issue. Since they both create, access, and delete the resource with the same name.

Go runs tests in a parallel way. We need to add a concurrent lock for test cases trying to access the same resources in openwhisk.

**Comment by houshengbo** [comment]
@mrutkows @pritidesai 
We run into this concurrent issue, for some of our test cases, since they are creating, accessing and deleting resources at the same time.

**Comment by mrutkows** [comment]
@houshengbo @pritidesai can we identify where we have overlapping names in our int. tests and assure we have unique names for each? at least for now?

**Comment by pritidesai** [comment]
Its the result of having copy/pasted deployment file from the integration test which was added in the beginning. This is the deployment file in **flagstests** with application name `wskdeploy-samples` and packaging name `triggerrule`: 

https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/tests/src/integration/flagstests/deployment.yml

```
application:
  name: wskdeploy-samples

  package:
    triggerrule:
      name: helloworld
      namespace: guest
      actions:
        greeting:
          inputs:
            name: Bernie
            place: Vermont
```

Depoyment file in **triggerrule:**

https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/tests/src/integration/triggerrule/deployment.yml

```
application:
  name: wskdeploy-samples

  package:
    triggerrule:
      name: helloworld
      namespace: guest
      actions:
        greeting:
          inputs:
            name: Bernie
            place: Vermont
```

Deployment file in **webaction**:

https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/tests/src/integration/webaction/deployment.yml

```
application:
  name: wskdeploy-samples

  package:
    triggerrule:
      name: helloworld
      namespace: guest
      actions:
        greeting:
          inputs:
            name: Bernie
            place: Vermont
```

Deployment file in **zipaction**:

https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/tests/src/integration/zipaction/deployment.yml

```
application:
  name: wskdeploy-samples
  package:
    triggerrule:
      name: cat
      namespace: guest
      actions:
        greeting:
          inputs:
            name: Bernie
            place: Vermont
```

We have four integration tests which have deployment files and the content is same for all (package name **triggerrule** and application name **wskdeploy-samples**)
