### ISSUE TITLE
Manifest parser needs to find Manifests in subdirectories within GitHub

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#430]
Currently, our parser will only find manifest files (i.e., manifest.yaml) within the top-level GitHub project directory/folder.  We need to be able to allow manifests for packages to be referenced (and found and processed) if they are placed within sub-directories (or sub-folders) within a GitHub project repo. as well.

For example, if we specify a dependent (GitHub hosted) package within a manifest as follows:
```
package:
  name: TestGitHubDependency
  dependencies:
    ow-package:
      location: github.com/myrepo/openwhisk-packages
```

It will find, by default, the manifest.yaml within the "github.com/myrepo/openwhisk-app" top-level directory.

However, we also need it to support subdirectories as expressed in the following example:
```
package:
  name: TestGitHubDependency
  dependencies:
    ow-package-1:
      location: github.com/myrepo/openwhisk-packages/pkg1
    ow-package-1:
      location: github.com/myrepo/openwhisk-packages/pkg2
```

where a "manifest.yaml" file exists in both the "pkg1" and "pkg2" subdirectories, but there is NO manifest.yaml in the top-level project repo. folder (i.e., no manifest in github.com/myrepo/openwhisk-packages/).

Wskdeploy will have many GitHub integartion tests that will rely upon this ability (feature).
