### ISSUE TITLE
Create binding when dependency name and the origin package name are different

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-wskdeploy#437]
Below are `dependencies` samples. 
```
dependencies: 
    myCloudant:
      location: /whisk.system/cloudant
      inputs:
        dbname: myGreatDB
   myhelloworld:
      location: github.com/daisy-ycguo/wskdeploy-test/helloworld
```

Now we can define two kinds of dependencies:
- Binding to existing package, e.g. `myCloudant` in the sample.  We will create a package binding to `/whisk.system/cloudant` with the new package name as `myCloudant`.
- Dependency to an external source code in git repo, e.g. `myhelloworld` in the sample. We will deploy the package `myhelloworld` using the manifest file under folder `http://github.com/daisy-ycguo/wskdeploy-test/helloworld`.

If the dependency name is different than the origin package name, the reference to actions under this package will look weird. For example, the origin package name is `myhelloworld`, the dependency name is `dependency_name`. When I want to refer to an action under this package, I have to use `myhelloworld/helloworld`, not `dependency_name/helloworld`. Refer to below sample.
```
dependencies: 
   dependency_name:
      location: github.com/daisy-ycguo/wskdeploy-test/helloworld
sequences:
    mySequence:
      actions: myhelloworld/helloworld
```

So my question is how to handle if the dependency name is different with the origin package name. Maybe we can deploy the origin package at first and then create a binding with the dependency name. It might be a reasonable solution.

@mrutkows what's your suggestion?
