### ISSUE TITLE
Review apis in the specification

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-wskdeploy#438]
In the specification, there is a full grammar sample of `apis` and a simplified grammar sample (Refer to below). I think they are not consistent. According to the codes, I think `path` is not an element under `apis`. It should be a sub element under `basepath`. `actions` should be a sub element under `path`.
```
apis:
  book-club:
  description: Book Club
  basepath: /club
  path: /books
  actions:
    getBooks:
      verb: get
    postBooks:
      verb: post
    putBooks:
      verb: put
    deleteBooks:
      verb: delete
```
```
apis:
  book-club:
    club:
      books:
        getBooks: get
        postBooks: post
        putBooks: put
        deleteBooks: delete
```
