### ISSUE TITLE
api-gateway feature doesn't support full grammar manifest

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-wskdeploy#439]
Do we want the api-gateway feature to support the full grammar manifest ? If so, we need to add more test.

```
apis:
  book-club:
  description: Book Club
  basepath: /club
  path: /books
  actions:
    getBooks:
      verb: get
    postBooks:
      verb: post
    putBooks:
      verb: put
    deleteBooks:
      verb: delete
```

**Comment by mrutkows** [comment]
@daisy-ycguo we discussed how we changed (simplified) the grammar into asingle grammar in spec. version 0.8.8.

it appears as follows:
```
apis:
  <API name>:                    # descriptive name
    description: <string>        # optional, description
    <basepath>:                  # shared basepath
      <path>: 
         <action name>: get | post | put | delete
         ...
      ...
```

and example:
```
apis:
  book-club:
    club:
      books: 
        getBooks: get
        postBooks: post
        putBooks: put
        deleteBooks: delete
      members:
        listMembers: get
```
