### ISSUE TITLE
Does trigger have inputs ?

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-wskdeploy#449]
I checked the specification, trigger entity has 2 sub elements: `feed` and `events`. ( `events` is not supported at this time ).

But according to this [deployment](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/tests/usecases/alarmtrigger/deployment.yaml) file, trigger can have `inputs` element.
```
        triggers:
            Every12Hours:
                inputs:
                    cron: "0 */12 * * *"
```

Please review the trigger entity definition in specification, @mrutkows
