### ISSUE TITLE
Trigger supports "source" according to the code, yet spec has "feed" as trigger sub element.

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-wskdeploy#450]
We should support `feed` under `trigger`, mark `source` deprecated.

In the use case `alarmtrigger`, a trigger is described as below.
```
package:
    name: helloworld
    triggers:
        Every12Hours:
            source: /whisk.system/alarms/alarm
```
If I change `source` to `feed`, it will create a trigger without `feed` in OpenWhisk.
```
$ wsk trigger get Every12Hours
ok: got trigger Every12Hours
{
    "namespace": "guoyingc@cn.ibm.com_dev",
    "name": "Every12Hours",
    "version": "0.0.1",
    "parameters": [
        {
            "key": "cron",
            "value": "0 */12 * * *"
        }
    ],
    "limits": {},
    "publish": false
}
```
