### ISSUE TITLE
Update Dependency use case to use incubator-openwhisk-test packages

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#464]
This relates to the PR: https://github.com/apache/incubator-openwhisk-wskdeploy/pull/461

which fixed the Dependency use case but still uses dependent packages:
```
    hellowhisk:
      location: github.com/paulcastro/hellowhisk
    myhelloworld:
      location: github.com/daisy-ycguo/wskdeploy-test/helloworld
```

We have moved Paul's package (from 'paulcastro' repo.) to incubator-openwhisk-test repo. and we will want to update this use case to reference it there. In addition, we need to move your package (from 'daisy-ycguo' repo.) there too so there are no private repo. names that are not part of the Apache GitHub referenced.
