### ISSUE TITLE
 WIP : A trigger feed is only permitted when the trigger is created (Priti)

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#480]
When `wskdeploy` is run multiple times in `deployment` mode fails with error `A trigger feed is only permitted when the trigger is created (code 38299346) Error code: 144.`  I think `wskdeploy` should not throw failure, instead it can check if feed exists then ignore it. Its little impractical to update manifest/deployment files for subsequent deployments of the same package. 

**manifest.yaml:**

```
package:
    name: helloworld
    actions:
        helloworld:
            function: actions/hello.js
            runtime: nodejs:6
            inputs:
                name:
                    type: string
                    description: name of a person
                place:
                    type: string
                    description: location of a person
            outputs:
                payload:
                    type: string
                    description: a simple greeting message, Hello World!
    triggers:
        Every12Hours:
            feed: /whisk.system/alarms/alarm
    rules:
        helloworldEvery12Hours:
            action: helloworld
            trigger: Every12Hours
```

**deployment.yaml**

```
application:
    name: HelloWorldEvery12Hours
    namespace: _
    packages:
      helloworld:
        actions:
            helloworld:
                inputs:
                    name: Amy
                    place: Paris
        triggers:
            Every12Hours:
                inputs:
                    cron: "0 */12 * * *"
```

```
[15] -> ./wskdeploy -p tests/usecases/alarmtrigger/
Done!
Done!
Done!
Done!
Deployment completed successfully.


 [16] -> ./wskdeploy -p tests/usecases/alarmtrigger/
Done!
Done!
Error: /Users/pritidesai/Documents/goworkspace/src/github.com/apache/incubator-openwhisk-wskdeploy/deployers/servicedeployer.go [508]: OpenWhisk Client Error =====> A trigger feed is only permitted when the trigger is created (code 38299346) Error code: 144.
Usage:
  wskdeploy [flags]
  wskdeploy [command]

Available Commands:
  add         Add an action, feed, trigger or rule to the manifest
  help        Help about any command
  init        Init helps you create a manifest file on OpenWhisk
  publish     Publish a package to a registry
  report      Returns summary of what's been deployed on OpenWhisk in specific namespace
  undeploy    Undeploy assets from OpenWhisk
  version     Print the version number of openwhisk-wskdeploy

Flags:
  -a, --allow-defaults       allow defaults
  -i, --allow-interactive    allow interactive prompts
      --apihost string       whisk API HOST
      --apiversion VERSION   whisk API VERSION
  -u, --auth KEY             authorization KEY
      --config string        config file (default is $HOME/.wskprops)
  -d, --deployment string    path to deployment file
  -h, --help                 help for wskdeploy
  -m, --manifest string      path to manifest file
  -n, --namespace string     namespace
  -p, --pathpath string      path to serverless project (default ".")
  -t, --toggle               Help message for toggle
  -v, --verbose              verbose output

Use "wskdeploy [command] --help" for more information about a command.

Error: /Users/pritidesai/Documents/goworkspace/src/github.com/apache/incubator-openwhisk-wskdeploy/deployers/servicedeployer.go [508]: OpenWhisk Client Error =====> A trigger feed is only permitted when the trigger is created (code 38299346) Error code: 144.

```
