### ISSUE TITLE
Github feed example shows "function" as valid key for Feed 

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#495]
Github feed example shows this as valid:

```
git_webhook:
  version: 1.0
  license: Apache-2.0
  feeds:
    webhook_feed:
      version: 1.0
      **function**: github/webhook.js
      runtime: nodejs@6
```

however, "functions" is not supported in the actual spec.  Perhaps this is an attempt at some shortcut that we have not discussed/vetted properly?  

The only way to ref a function is indirectly, using an "action" (i.e. the name of an action also declared in the manifest file.
