### ISSUE TITLE
WIP: Do we support packages in manifest file?

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#499]
Check wether we have support for `packages` in manifest file. Add if we don't have one.

All our manifests are defined with `package`, change them to use `packages` such as:

```
packages:
    <package1>:
     ....
     <package2>:
     ...
```

**Comment by mrutkows** [comment]
@pritidesai let's discuss if we should break this into 2 issues.

**Comment by mrutkows** [comment]
currently, our code looks for the word "package" and strictly looks for the key word "name" as follows:

```
package:
  name: hello_world_package
  version: 1.0
  license: Apache-2.0
  actions:
    hello_world:
      function: src/hello.js
```
This is fine. However, according to the spec. and what user have asked for we need to support this simpler alternative:

```
package:
  hello_world_package:
    version: 1.0
    license: Apache-2.0
    actions:
      hello_world:
        function: src/hello.js
```
where "name" is implied to be "hello_world_package" (and not an error as is what happens now).

This allows us then to have multiple named "packages" (plural keyword) within the same "application:" structure.  That is we should support the keyword "packages"; where 1..N packages would be supported.
```
packages:
  hello_world_package_1:
    version: 1.0
    license: Apache-2.0
  hello_world_package_2:
    version: 1.0
    license: Apache-2.0
    ...
  hello_world_package_N:
    version: 1.0
    license: Apache-2.0
```
of course, we SHOULD throw an error if NO packages are found in either case (minimum of 1 if either keyword is used in the YAML).
