### ISSUE TITLE
Enforce Credentials from each package in manifest file

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#563]
When we added support for `packages` in manifest file in which it can have multiple `packages` with multiple `credentials` i.e. deploying each package to different openwhisk instance.

**Manifest file:**

```
packages:
  helloworld-1:
    namespace: <namespace>
    credential: <credentails>
    apiHost: <apiHost>
    actions:
      ...
  helloworld-2:
    namespace: <namespace>
    credential: <credentails>
    apiHost: <apiHost>
    actions:
      ...
```

This functionality is not currently supported which needs to be fixed. At this point,in this kind of use case `wskdeploy` ignores `credentials` from the manifest file if it has more than one packages.
