### ISSUE TITLE
Deployment file should not require "application" key if manifest does not

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#572]
This deployment file throws an error:
```
  packages:
      hello_world_package:
        triggers:
          meetPerson:
            inputs:
              name: Elrond
              place: Rivendell
              children: 3
              height: 1.88
```

this does not:
```
application:
  packages:
      hello_world_package:
        triggers:
          meetPerson:
            inputs:
              name: Elrond
              place: Rivendell
              children: 3
              height: 1.88
```
manifests can have their outermost document key be either "package" or "packages"; this should also be allowed for corresponding Deployment files.

Additionally,  if the deployment file DOES contain an application with a "name"  AND the manifest also contains an application "name" we should ERROR if there is a mismatch.
