### ISSUE TITLE
Annotations on Actions only work if "web export" exists

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#609]
It appears at some point (perhaps when we added support for "web actions" that the ComposeActions() function has logic that ONLY creates Annotations on the wskAction IFF ```action.Webexport == "true"```. 

To make matters more convoluted, even if "Webexport==true", the annotations are created as a "side effect" of calling ```utils.WebAction```; this is not good coding practice.

```		keyValArr = make(whisk.KeyValueArr, 0)
		for name, value := range action.Annotations {
			var keyVal whisk.KeyValue
			keyVal.Key = name
			keyVal.Value = utils.GetEnvVar(value)
			keyValArr = append(keyValArr, keyVal)
		}

		// only set the webaction when the annotations are not empty.
		if action.Webexport == "true" {
			// TODO() why is this commented out?  we should now support annotations...
			//wskaction.Annotations = keyValArr
			wskaction.Annotations, errorParser = utils.WebAction("yes", keyValArr, action.Name, false)
			if errorParser != nil {
				return s1, errorParser
			}
		}
```

we have NO testcases for Annotations on Actions (only for Triggers) and need several as part of fixing this issue.  The Annotations SHOULD work with or without "webExport==true" and NOT be a side effect.

**Comment by pritidesai** [comment]
I am running some sample tests to determine `wskdeploy` behavior for annotations on actions and found these facts:

- If an action in manifest file has `annotations` section, the whole section is ignored and not added to action creation statement.

**manifest.yaml**

```
packages:
    packagebinding:
        actions:
            helloworld:
                function: actions/helloworld.js
                runtime: nodejs:6
                annotations:
                    action_annotation_1: hello
                    action_annotation_2: this is an annotation
```

- If an action in deployment file has `annotations`, the entire list of annotations are added to action creation.

**deployment.yaml**

```
application:
  name: BindingTest
  packages:
    packagebinding:
      actions:
        helloworld:
          annotations:
            tag: hello
            aaa: this is an annotation
```

- When an action in manifest file has `annotations` section and an action in deployment file has `annotations` section, only `annotations` from deployment file is added to action creation. @mrutkows how should `wskdeploy` behave in this use case? combine action annotations from both manifest and deployment?

(TODO) what happens when annotations and web export both are specified in manifest file?
