### ISSUE TITLE
Provide support for an env_variable for package name

### ISSUE THREAD

**Issue by beemarie** [apache/incubator-openwhisk-wskdeploy#610]
Currently in the deploy package, if we want to provide a different package name, we are parsing the file & renaming the package name node.  Would it be possible to provide support for an optional environment variable as the package name?

**Comment by csantanapr** [comment]
@mrutkows @houshengbo @daisy-ycguo 
The sample is the following, we want to be able to have a manifest of this form
```
package:
  name: $MY_AWESOME_PACKAGE
  version: 1.0
  license: Apache-2.0
  namespace: _
  actions:
    helloworld:
      function: actions/helloworld.js
```
And  use the environment variable `MY_AWESOME_PACKAGE`  for the package name.

@beemarie what's the current behavior? you get an error in wskdeploy?

**Comment by houshengbo** [comment]
@beemarie @csantanapr 
We are deprecating the format in the previous comment. Here is the new format looks like:
```
packages:
  PACKAGE_NAME:
    version: 1.0
    license: Apache-2.0
    namespace: _
    actions:
      helloworld:
        function: actions/helloworld.js
```
Do we need the package name able to read from env variable supported for the new format?
Besides, is it only for package name? We also have trigger name, dependency name, rule name, etc.

I have to say that if we support env variables to be picked up by the manifest, it can be even more complicated to maintain the yaml files, because there can be multiple env variables to manage.

**Comment by beemarie** [comment]
@houshengbo @csantanapr 
It is more important to be able to provide PACKAGE_NAME as an env-variable over trigger name, rule name, etc., as packages can not be renamed once created.

**Comment by mrutkows** [comment]
it could be implemented as a new feature easily with exiting code; however, we are moving away from “package” to “packages” and then it becomes more difficult...

Currently, "packages" follows our consistent convention/pattern to use names as "keys" (or IDs) in the YAML document. The YAML parser may not handle having and odd string (it might though would have to try it with the go-yaml parser).  If the parser cannot handle it, then we would have to assure we had the “name” (or similar) field as a valid field for “packages” and make sure we replaced the name on the API call.

**Comment by mrutkows** [comment]
@houshengbo also be aware that we allow "partial" replacement as well...
e.g.
```
packages:
  IBM-{$PACKAGE_NAME}:
    version: 1.0
    license: Apache-2.0
    namespace: _
    actions:
      helloworld:
        function: actions/helloworld.js
```
