### ISSUE TITLE
Allow "headless" yaml tree for "projects" (f.k.a. "applications")

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#618]
Need to look to see if we can support an implicit "project" (i.e., "application") in a YAML manifest without the keyword "application" or "project" appearing.

This may be challenging as we may do this already for "package". 

- Please use this issue to investigate and report findings....

**Comment by mrutkows** [comment]
Please see related issue https://github.com/apache/incubator-openwhisk-wskdeploy/issues/617 which is adding support for the explicit "project" key.

**Comment by pritidesai** [comment]
We do support headless yaml tree such as:

```
packages:
    package-1:
        actions:
        ....
```

along with:

```
project:
    name: myProject
    packages:
        package-1:
            actions:
             ....
```
