### ISSUE TITLE
proper handling of 'default' package name

### ISSUE THREAD

**Issue by lionelvillard** [apache/incubator-openwhisk-wskdeploy#681]
'default' is a reserved package name. wskdeploy should use this name to deploy actions in the _package without name_ (e.g /ns/actionname)

**Comment by pritidesai** [comment]
As package `default` is a reserved package name, when we invoke `wskdeploy` with this kind of manifest:

```
packages:
   default:
      actions:
        # helloworld action in NodeJS
        helloNodejs:
          function: actions/hello.js
...
```
It fails with:

```
./wskdeploy -p tests/src/integration/helloworld/
...
Error: Deployment did not complete sucessfully. Run `wskdeploy undeploy` to remove partially deployed assets.
Error: servicedeployer.go [1499]: [ERROR_WHISK_CLIENT_ERROR]: Error code: 144: Package name 'default' is reserved. (code 26402220): HTTP Response Status: 400 Bad Request HTTP Response Body: {"error":"Package name 'default' is reserved.","code":26402220}
```

We have to add support for this kind of manifest where package name is set to `default` and create all entities from the manifest file directly under namespace. To support this, add a check before creating package, if package name is set to `default`, skip package creation and reflect it in every entity creation requests. Instead of sending PUT request to `namespaces/guest/actions/default/helloNodejs?overwrite=true` send it to `namespaces/guest/actions/helloNodejs?overwrite=true`

**Comment by mrutkows** [comment]
Hmmm... I am not sure if I like that a tool-decided behavior as to where to relocate (under namespace directly) and it is not documented anywhere.  Since "default" does indeed exist (you can view it), but cannot add/update/delete it, it seems that perhaps (for now) an error would be appropriate since I would not want to confuse people since we ack. that "default" doe exits (but it is reserved).  Perhaps we need another keyword or grammar change to support deploying directly to namespace. BUT wskpdeploy is Package-oriented and goes against NOT properly organizing projects... in fact I would rather encourage OW to move in the opposite direction, that is, to allow more namespace Paths (allow for Project to be a path). After all, this hardcoded-tuple path we have now really is not justified and does not mesh with general URI strategy for IBM.

**Comment by mrutkows** [comment]
@lionelvillard thoughts? ^^^

**Comment by lionelvillard** [comment]
what about allowing `actions` (and `rules` and `triggers`) to be specified at the top-level?

```
packages:
  boo:
    actions:
      ...
actions:
  ...
```

**Comment by ScottChapman** [comment]
I @lionelvillard proposal makes sense. Seems to fit with the OW model (root of the namespace).

**Comment by csantanapr** [comment]
I also think agree with @lionelvillard let’s allow to be at the root for actions, rules, triggers

**Comment by kpavel** [comment]
Agree with @lionelvillard, rules and triggers should be placed at the top level to reflect OW model. Maybe should consider to place sequences there as well.

**Comment by pritidesai** [comment]
After talking to Matt and scoping this feature of creating OW entities under `namespace/` rather than `namespace/<package>`, its much more feasible (from time, complexity, compatibility, and consistency perspective) to add support for package name `default` in `wskdeploy`. When a package name is set to `default` in manifest/deployment files, `wskdeploy` will generate warnings (1) `Package name 'default' is reserved.` and (2) all OW entities specified in manifest file under `default` package will be created  under your namespace `<namespace>/`.

For example, action `helloNodejs`, trigger `locationUpdate`, and rule `hellorule` in the following example will be created under `<namespace>/` 
```
packages:
   default:
      actions:
        # helloworld action in NodeJS
        helloNodejs:
          function: actions/hello.js
      triggers:
        locationUpdate:
      rules:
        hellorule:
          trigger: locationUpdate
          action: helloNodejs
```

Priority: Critical
