### ISSUE TITLE
How do I create package parameters?

### ISSUE THREAD

**Issue by ScottChapman** [apache/incubator-openwhisk-wskdeploy#702]
I have a package where I create a single parameter using a JSON object as the value. I do this manually now with wsk action create ... -P PackageParams.json where the file contains something like:
```
{
   "credentials": {
      "username": "something",
      "password": "something else"
   }
}
```

How would that manifest in the YML exactly?

**Comment by pritidesai** [comment]
@ScottChapman  please try using this manifest:

```
packages:
    validate_json: #this is a package name
        actions:
            validate_json_params: # this is a action name
                function: actions/dump_params.js
                runtime: nodejs:6
                inputs:
                    credentials:
                        type: json
                        value: '{ "username": "something", "password": "something else" }'
```
