### ISSUE TITLE
Action: Web (export): Support web-custom-options annotation

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#711]
See: https://github.com/apache/incubator-openwhisk/blob/master/docs/annotations.md

**Comment by pritidesai** [comment]
This is supported with `wskdeploy` annotations:

```
            greeting-web-action-with-custom-options:
                web-export: true
                version: 1.0
                function: src/greeting.js
                runtime: nodejs:6
                annotations:
                    web-custom-options: true
```

Verification:

```
wsk action get IntegrationTestWebAction/greeting-web-action-with-custom-options
ok: got action IntegrationTestWebAction/greeting-web-action-with-custom-options
{
    "namespace": "guest/IntegrationTestWebAction",
    "name": "greeting-web-action-with-custom-options",
    "version": "0.0.1",
    "exec": {
        "kind": "nodejs:6",
        "code": "/**\n * Return a simple greeting message for someone.\n *\n * @param name A person's name.\n * @param place Where the person is from.\n */\nfunction main(params) {\n    var name = params.name || params.payload || 'stranger';\n    var place = params.place || 'somewhere';\n    return {payload:  'Hello, ' + name + ' from ' + place + '!'};\n}\n",
        "binary": false
    },
    "annotations": [
        {
            "key": "web-export",
            "value": true
        },
        {
            "key": "web-custom-options",
            "value": true
        },
        {
            "key": "raw-http",
            "value": false
        },
        {
            "key": "final",
            "value": true
        },
        {
            "key": "exec",
            "value": "nodejs:6"
        }
    ],
    "limits": {
        "timeout": 60000,
        "memory": 256,
        "logs": 10
    },
    "publish": false
}
```
