### ISSUE TITLE
Action: Web (action): Support the require-whisk-auth annotation

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#712]
See: https://github.com/apache/incubator-openwhisk/blob/master/docs/annotations.md

**Comment by pritidesai** [comment]
This is already supported as `wskdeploy` supports annotations and can be defined as:

```
           greeting-web-action-with-auth:
                web-export: true
                version: 1.0
                function: src/greeting.js
                runtime: nodejs:6
                annotations:
                    require-whisk-auth: true
```

Verifying:


```
wsk action get IntegrationTestWebAction/greeting-web-action-with-auth
ok: got action IntegrationTestWebAction/greeting-web-action-with-auth
{
    "namespace": "guest/IntegrationTestWebAction",
    "name": "greeting-web-action-with-auth",
    "version": "0.0.1",
    "exec": {
        "kind": "nodejs:6",
        "code": "/**\n * Return a simple greeting message for someone.\n *\n * @param name A person's name.\n * @param place Where the person is from.\n */\nfunction main(params) {\n    var name = params.name || params.payload || 'stranger';\n    var place = params.place || 'somewhere';\n    return {payload:  'Hello, ' + name + ' from ' + place + '!'};\n}\n",
        "binary": false
    },
    "annotations": [
        {
            "key": "web-export",
            "value": true
        },
        {
            "key": "raw-http",
            "value": false
        },
        {
            "key": "final",
            "value": true
        },
        {
            "key": "require-whisk-auth",
            "value": true
        },
        {
            "key": "exec",
            "value": "nodejs:6"
        }
    ],
    "limits": {
        "timeout": 60000,
        "memory": 256,
        "logs": 10
    },
    "publish": false
}
```
