### ISSUE TITLE
API Gateway - Add support to specify response type in manifest file

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#724]
APIs are defined in manifest file with:

```
    apis:
           book-club:
                club:
                    books:
                        getBooks: GET
                        postBooks: POST
                        putBooks: PUT
                        deleteBooks: DELETE
```

Now, here four different APIs are getting created with specified Gateway Method (GET, POST, PUT, DELETE, etc), with default response type of `json`. As this current schema does not support specifying response type for each API. We need to update the schema so that response type can be specified, some possible options:

```
    apis:
           book-club:
                club:
                    books:
                        getBooks: GET,<response_type>
                        postBooks: POST,<response_type>
                        putBooks: PUT,<response_type>
                        deleteBooks: DELETE,<response_type>
```

or:

```
    apis:
           book-club:
                club:
                    books:
                        getBooks:
                            method: GET
                            response: <response_type>
                        postBooks:
                            method: POST
                            response: <response_type>
                        putBooks:
                            method: PUT
                            response: <response_type>
                        deleteBooks:
                            method: DELETE
                            response: <response_type>
```

please feel free to suggest any other option.

**Comment by pritidesai** [comment]
@brunogirin @csantanapr @mrutkows please provide your feedback for the design.

**Comment by pritidesai** [comment]
Moving it to high priority as @brunogirin looking for this fix.

**Comment by csantanapr** [comment]
I like the second better
```
    apis:
           book-club:
                club:
                    books:
                        getBooks:
                            method: GET
                            response: <response_type>
                        postBooks:
                            method: POST
                            response: <response_type>
                        putBooks:
                            method: PUT
                            response: <response_type>
                        deleteBooks:
                            method: DELETE
                            response: <response_type>
```

**Comment by mrutkows** [comment]
This is the PR that added the support to the CLI: https://github.com/apache/incubator-openwhisk-cli/pull/170

**Comment by brunogirin** [comment]
So does it mean that you could also have?

```
apis:
           book-club:
                club:
                    books:
                        getBook/{bookId}:
                            method: GET
                            response: http
```

Or would the response type automatically be set to `http` if the URL has path arguments?
