### ISSUE TITLE
Remove empty maps/interfaces from "export" manifest yaml

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#729]
all empty maps and interfaces should be removed from the final manifest; also, we should remove any deprecated keys in favor of latest keys (this may mean moving maps (subtrees) from deprecated keys to the ones now in spec.

This is what we produce today:
```
application:
  name: ""
  namespace: ""
  credential: ""
  apiHost: ""
  version: ""
  packages: {}
  package:
    name: ""
    version: ""
    license: ""
    dependencies: {}
    namespace: ""
    credential: ""
    apiHost: ""
    actions: {}
    triggers: {}
    feeds: {}
    rules: {}
    inputs: {}
    sequences: {}
    apis: {}
project:
  name: MyFirstManagedProject
  namespace: ""
  credential: ""
  apiHost: ""
  version: ""
  packages: {}
  package:
    name: ""
    version: ""
    license: ""
    dependencies: {}
    namespace: ""
    credential: ""
    apiHost: ""
    actions: {}
    triggers: {}
    feeds: {}
    rules: {}
    inputs: {}
    sequences: {}
    apis: {}
packages:
  ManagedPackage-1:
    name: ManagedPackage-1
    version: 0.0.2
    license: ""
    dependencies: {}
    namespace: guest
    credential: ""
    apiHost: ""
    actions:
      HelloWorld-1:
        version: 0.0.2
        location: ""
        function: ManagedPackage-1/HelloWorld-1.js
        runtime: nodejs:6
        namespace: guest/ManagedPackage-1
        credential: ""
        inputs:
          name:
            value: ""
          place:
            value: ""
        outputs: {}
        name: HelloWorld-1
        exposedUrl: ""
        web-export: ""
        main: ""
        limits: null
      HelloWorld-2:
        version: 0.0.2
        location: ""
        function: ManagedPackage-1/HelloWorld-2.js
        runtime: nodejs:6
        namespace: guest/ManagedPackage-1
        credential: ""
        inputs:
          name:
            value: ""
          place:
            value: ""
        outputs: {}
        name: HelloWorld-2
        exposedUrl: ""
        web-export: ""
        main: ""
        limits: null
      HelloWorld-3:
        version: 0.0.2
        location: ""
        function: ManagedPackage-1/HelloWorld-3.js
        runtime: nodejs:6
        namespace: guest/ManagedPackage-1
        credential: ""
        inputs:
          name:
            value: ""
          place:
            value: ""
        outputs: {}
        name: HelloWorld-3
        exposedUrl: ""
        web-export: ""
        main: ""
        limits: null
    triggers:
      ManagedTrigger-1:
        feed: ""
        namespace: guest
        credential: ""
        inputs: {}
        name: ManagedTrigger-1
        source: ""
    feeds: {}
    rules: {}
    inputs: {}
    sequences:
      ManagedSequence-1:
        actions: HelloWorld-1,HelloWorld-2,HelloWorld-3
      ManagedSequence-2:
        actions: HelloWorld-1,HelloWorld-2,HelloWorld-3
    apis: {}
package:
  name: ""
  version: ""
  license: ""
  dependencies: {}
  namespace: ""
  credential: ""
  apiHost: ""
  actions: {}
  triggers: {}
  feeds: {}
  rules: {}
  inputs: {}
  sequences: {}
  apis: {}
filepath: ""
```

**Comment by allen-servedio** [comment]
Just another comment on this... It is very unclear at what level you are supposed to define things - esp. since it appears multiple levels will work.

This works:

```
project:
  name: MyProject
  namespace: org_space
  version: 0.0.1
  packages:
    rediskv:
      license: Apache-2.0
      inputs: 
        redisURL:
          type: string
          description: Redis database URL
      actions: 
        kvget:
          function: retrieve/index.js
          runtime: nodejs
        kvput:
          function: store/index.js
          runtime: nodejs
```

However, this does NOT see the package or action:

```
project:
  name: MyProject
  namespace: org_space
  version: 0.0.1
  package:
    name: rediskv
    license: Apache-2.0
    inputs: 
      redisURL:
        type: string
        description: Redis database URL
    actions: 
      kvget:
        function: retrieve/index.js
        runtime: nodejs
      kvput:
        function: store/index.js
        runtime: nodejs
```

But, if you change the indention level it DOES see the package and actions:

```
project:
  name: MyProject
  namespace: org_space
  version: 0.0.1
package:
  name: rediskv
  license: Apache-2.0
  inputs: 
    redisURL:
      type: string
      description: Redis database URL
  actions: 
    kvget:
      function: retrieve/index.js
      runtime: nodejs
    kvput:
      function: store/index.js
      runtime: nodejs
```

This this also sees the package and actions:

```
project:
  name: MyProject
  namespace: org_space
  version: 0.0.1
packages:
  rediskv:
    license: Apache-2.0
    inputs: 
      redisURL:
        type: string
        description: Redis database URL
    actions: 
      kvget:
        function: retrieve/index.js
        runtime: nodejs
      kvput:
        function: store/index.js
        runtime: nodejs
```

So anything that can be done to clearly define how these are supposed to be put together would really help.
