### ISSUE TITLE
Add support for credentials for private git repo dependencies

### ISSUE THREAD

**Issue by allen-servedio** [apache/incubator-openwhisk-wskdeploy#735]
Dependencies allows you to define a location and version of the artifact that you want to use. Here is an example:

```
project:
  name: MyProject
  version: 0.0.1
  packages:
    mypackage:
      license: Apache-2.0
      version: 0.0.1
      dependencies:
        mydep:
          location: https://github.com/my-org/my-private-repo
          version: 0.0.1
```

However, there does not appear to be a way to define credentials for accessing this repository - which is required for private repos.

The error you get when you try to do this is also not great (it is calling: https://github.com/my-org/my-private-repo/zipball/0.0.1):

```
Error: manifestreader.go [103]: [ERROR_YAML_FILE_FORMAT_ERROR]: File: [manifest.yaml]:
==> manifestreader.go [147]: [ERROR_YAML_FILE_FORMAT_ERROR]: File: [mypackage]:
==> ==> zip: not a valid zip file
==>
```

What is actually happening is the call results in a 404 from github.
