### ISSUE TITLE
Add top level package definition and it ignores packages

### ISSUE THREAD

**Issue by allen-servedio** [apache/incubator-openwhisk-wskdeploy#742]
In the configuration below, the ONLY thing that will be deployed is the package defined at the end of the file. It ignores the packages section that describes the dependency:

```
project:
  name: WskDeployWithDeps
  version: 0.0.2
  packages:
    myrediskv:
      license: Apache-2.0
      version: 0.0.2
      namespace: my-namespace
      dependencies:
        poc-common-func:
          location: https://github.com/my-org/my-project
          version: 0.0.1
          inputs: 
            redisURL:
              type: string
              value: my-url-goes-here
              description: Redis database URL
package:
  name: rediskv
```

This was found in #740

**Comment by pritidesai** [comment]
@allen-servedio this is a deprecated schema and we are working on taking support out for the same, the plan was to maintained old schema for backward compatibility for sometime last year.

**Comment by pritidesai** [comment]
also @allen-servedio please refer to https://github.com/apache/incubator-openwhisk-wskdeploy/tree/master/tests/src/integration for any working example and best practices on writing manifest/deployment files.

**Comment by allen-servedio** [comment]
Understood, but the behavior it displays is surprising. Namely that when you add the deprecated package definition to your manifest, it ignores the "project -> packages" definitions.

**Comment by pritidesai** [comment]
With @mrutkows recent changes, top level `package` definition is now not supported and reported as fatal error:

`manifest.yaml`:

```
package:
    name: test
packages:
  IntegrationTestHelloWorld:
      actions:
        # helloworld action in NodeJS
        helloNodejs:
          function: actions/hello.js
          runtime: nodejs:6
          inputs:
            name:
              type: string
              description: name of a person
            place:
              type: string
              description: location of a person
          outputs:
            payload:
              type: string
              description: a simple greeting message, Hello World!
```

```
./wskdeploy -m manifest.yaml 
Info: The API host is [openwhisk.ng.bluemix.net], from .wskprops.
Info: The auth key is set, from .wskprops.
Info: The namespace is [_], from .wskprops.
Info: The apigw access token is set, from .wskprops.
Info: Unmarshal OpenWhisk runtimes from internet at https://openwhisk.ng.bluemix.net.
Error: manifest_parser.go [104]: [ERROR_YAML_PARSER_ERROR]: File: [manifest.yaml]: 
==> yaml: unmarshal errors:
==> line 17: field package not found in struct parsers.YAML
```
