### ISSUE TITLE
inline function does not work

### ISSUE THREAD

**Issue by lionelvillard** [apache/incubator-openwhisk-wskdeploy#745]
My manifest:

```
project:
  name: testfsh
packages:
  p:
    actions:
      echo:
        runtime: nodejs
        function: const main = ({ msg }) => { console.log(msg); return {msg}; }
```

I'm not sure if this is supposed to work or not. I'm getting this error:

```
Error: manifestreader.go [78]: [ERROR_YAML_FILE_FORMAT_ERROR]: File: [manifest.yml]:
==> open /Users/villardl/Projects/whisk/wskp/shell-project-test/const main = ({ msg }) => { console.log(msg); return {msg}; }: no such file or directory
```
