### ISSUE TITLE
Automatically add "web-export" to each Action referenced in the "apis" (key) section

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#752]
The user of the schema should not have to add this manually to each action; we can provide an information message that "wskdeploy" added "enabled web-export for Action X since it was referenced on an API".

As you can see this is cumbersome as shown by our unit test in manifest_parser_test.go:
```
// TODO() We SHOULD automatically add "web-export" to each Action referenced in the "apis" section
// as this is implied.  The user should not have to do this manually
func TestComposeApiRecords(t *testing.T) {
packages:
  apiTest:
    actions:
      putBooks:
        function: ../tests/src/integration/helloworld/actions/hello.js
        web-export: true
      deleteBooks:
        function: ../tests/src/integration/helloworld/actions/hello.js
        web-export: true
      listMembers:
        function: ../tests/src/integration/helloworld/actions/hello.js
        web-export: true
      getBooks2:
        function: ../tests/src/integration/helloworld/actions/hello.js
        web-export: true
      postBooks2:
        function: ../tests/src/integration/helloworld/actions/hello.js
        web-export: true
      listMembers2:
        function: ../tests/src/integration/helloworld/actions/hello.js
        web-export: true
    apis:
        ...
```

of course, if we "export" they will see we did this for them...
