### ISSUE TITLE
Introduce Conductor in manifest/deployment file

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#782]
Here is the documentation on coductor:
https://github.com/apache/incubator-openwhisk/blob/master/docs/conductors.md

Conductor action can be created by adding the `conductor` annotation like:

```
wsk action create tripleAndIncrement tripleAndIncrement.js -a conductor true
```

This kind of annotation is already supported and can be specified in manifest file with:

```
packages:
    ConductorAction:
        actions:
            tripleAndIncrement:
                function: tripleAndIncrement.js
                annotations:
                    conductor: true
```

But in order to make it little more easier, lets add `conductor` as a separate key in manifest file.
