### ISSUE TITLE
Report - Parameters in JSON form

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#803]
Scott from watson has shown interest in spitting out JSON data structure with all the `inputs` from every OW entities, something like this:

manifest.yaml/deployment.yaml:

```
packages:
    validate:
        actions:
            myaction:
                function: actions/dump_params.js
                runtime: nodejs:6
                inputs:
                    param1:
                        type: string
                        value: foo
                    param2:
                        type: json
                        value: { "name": "${USERNAME}", "password": "${PASSWORD}" }
                    param3:
                        type: json
                        value: { "name": "$${USERNAME}", "password": "$${PASSWORD}" }
                    param4:
                        type: json
                        value: { "name": "${MISSING_ENV_VAR}" }
                    param5:
                        type: json
                        value: { "name": "${MISSING_ENV_VAR}",  "password": "${PASSWORD}" }
                    param6:
                        type: json
                        value: { "name": "${MISSING_ENV_VAR}",  "password": "${PASSWORD}", "username": "$${USERNAME}" }
```

Invoke `wskdeploy` with:

```
export USERNAME=MY_USERNAME
export PASSWORD=MY_PASSWORD
./wskdeploy report --params -m manifest.yaml
```

Output:

```
    "myaction": [
        {
            "name": "param1",
            "type": "string",
            "value": "foo"
            "description": "",
            "required": false,
            "missing_environment": []
        },
        {
            "name": "param2",
            "type": "json",
            "value": "{ "name": "MY_USERNAME", "password": "MY_PASSWORD" }"
            "description": "",
            "required": false,
            "missing_environment": []
        },
        {
            "name": "param3",
            "type": "json",
            "value": "{ "name": "${USERNAME}", "password": "${PASSWORD}" }"
            "description": "",
            "required": false,
            "missing_environment": []
        },
        {
            "name": "param4",
            "type": "json",
            "value": "{ "name": "${MISSING_ENV_VAR}" }"
            "description": "",
            "required": false,
            "missing_environment": ["MISSING_ENV_VAR"]
        },
        {
            "name": "param5",
            "type": "json",
            "value": "{ "name": "${MISSING_ENV_VAR}", "password": "MY_PASSWORD" }"
            "description": "",
            "required": false,
            "missing_environment": ["MISSING_ENV_VAR"]
        },
        {
            "name": "param6",
            "type": "json",
            "value": "{ "name": "${MISSING_ENV_VAR}", "password": "MY_PASSWORD", "username": "${USERNAME}" }"
            "description": "",
            "required": false,
            "missing_environment": ["MISSING_ENV_VAR"]
        },
```

@mrutkows comments/suggestions please? Couldn't come up with better name for list of missing env. variables.
