### ISSUE TITLE
wskdeploy export produces empty file

### ISSUE THREAD

**Issue by brunogirin** [apache/incubator-openwhisk-wskdeploy#880]
When I use `wskdeploy export`, it results in an empty file and going through the tool's help there doesn't seem to be any obvious missing flag that would result in this. This is on a project that has a number of actions, sequences and APIs and that deploys as expected with `wskdeploy`.

The exported file:

```yaml
project:
  name: ""
  namespace: ""
  credential: ""
  apiHost: ""
  apigwAccessToken: ""
  version: ""
  packages: {}
packages: {}
filepath: ""
```
