### ISSUE TITLE
Cannot use environment variables in action function parameters.

### ISSUE THREAD

**Issue by Logicon211** [apache/incubator-openwhisk-wskdeploy#891]
It took a bit of time to figure out that I couldn't use environment variables in the function path of an action.
Say for example I would like to make the location of a whisk archive configurable I attempted to do that using a small manifest.yaml like this:

```
project:
    name: test-wskdeploy
    packages:
      test-wskdeploy:
        version: 1.0.0
        actions:
          ping-1.0.0:
            function: https://${ARTIFACTORY_USER}:${ARTIFACTORY_API_KEY}@${ARTIFACTORY_URL}ping-${PING_VERSION}.zip
            runtime: nodejs:8
```

It fails to evaluate any of the variables in the function path. 

It would be useful to have this feature when using wskdeploy during automated builds and integration testing
