### ISSUE TITLE
wskdeploy export fails to export the `main` attribute for Java actions

### ISSUE THREAD

**Issue by brunogirin** [apache/incubator-openwhisk-wskdeploy#899]
When running `wskdeploy` on a project that has Java actions, it fails to export the `main` attribute for those actions, which means that the tool is then unable to re-deploy using the generated manifest.

## Steps to reproduce

1. Create a Java action that packaged in a jar file
2. Create a manifest that can deploy the action
3. Run `wskdeploy sync`
4. Run `wskdeploy export -m test-manifest.yml`: the manifest file is created
5. Run `wskdeploy sync -m test-manifest.yml`: it fails with error:

```
Error: Deployment did not complete sucessfully. Run `wskdeploy undeploy` to remove partially deployed assets.
Error: servicedeployer.go [1625]: [ERROR_WHISK_CLIENT_ERROR]: Error code: 144: The connection failed, or timed out. (HTTP status code 400): HTTP Response Status: 400 Bad Request HTTP Response Body: {"error":"The request content was malformed:\n'main' must be a string defined in 'exec' for 'java' actions","code":"c3ec2b5db6709d49c0a44cafb8620163"}
```

When inspecting the generated manifest, the definition of the Java action shows:

```
main: ""
```

## Expected behaviour

The tool should properly populate the `main` field in the Java action to ensure that it can be re-deployed.

**Comment by pritidesai** [comment]
@kpavel we have `action. Exec.Main` set in such cases, please populate `main` in manifest file using `action.Exec.Main`

**Comment by pritidesai** [comment]
Hi @brunogirin I have verified that @kpavel's changes has fixed this issue, the main function is now initialized in exported manifest:

```
   actions:                                                                       
      helloJava:                                                                   
        name: helloJava                                                            
        location: ""                                                               
        version: 0.0.1                                                             
        function: IntegrationTestExportHelloWorld/helloJava.jar                    
        code: ""                                                                   
        runtime: java                                                              
        namespace: _/IntegrationTestExportHelloWorld           
        credential: ""                                                             
        exposedUrl: ""                                                             
        web-export: ""                                                             
        web: ""                                                                    
        main: Hello                
```

Please verify ...
