### ISSUE TITLE
deploying manifest containing APIs with same backend action fails

### ISSUE THREAD

**Issue by kpavel** [apache/incubator-openwhisk-wskdeploy#916]
For example, result of deploying manifest below will be single API (h1 or h2 or h3) instead of expected three

```
packages:
    api-gateway-test1:
        version: 1.0
        license: Apache-2.0
        actions:
            greeting1:
                web-export: true
                version: 1.0
                function: src/greeting.js
                runtime: nodejs:6
        # new top-level key for defining groups of named APIs
        apis:
            h1:
                hello1:
                    world1:
                        greeting1: GET
            h2:
                hello2:
                    world2:
                        greeting1: GET
            h3:
                hello3:
                    world3:
                        greeting1: GET
```
