### ISSUE TITLE
Docs incorrect for apigateway syntax

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-wskdeploy#956]
The docs for apigateway, contains the wrong syntax to specify method.
```
    apis:
      hello-world:
        hello:
          world:
            hello_world: GET
```
It doesn't specify the new syntax
```
           book-club3:
                club3:
                    booksByISBN/{isbn}:
                        getBooks3:
                            method: get
                            response: http
```
